package com.utn.cookmate.ui.screens

object  Routes {

    const val ABOUT_SCREEN = "ABOUT_SCREEN"
    const val LOGIN_SCREEN = "LOGIN_SCREEN"
    const val CREATE_USER_SCREEN = "CREATE_USER_SCREEN"
    const val MIS_RECETAS_SCREEN = "MIS_RECETAS_SCREEN"
    const val SEGURO_ELIMINAR_RECETA_SCREEN = "SEGURO_ELIMINAR_RECETA_SCREEN"
    const val BUSCAR_RECETA_ONLINE_SCREEN = "BUSCAR_RECETA_ONLINE_SCREEN"
    const val RECETAS_ENCONTRADAS_SCREEN = "RECETAS_ENCONTRADAS_SCREEN"
    const val PASO_A_PASO_SCREEN = "PASO_A_PASO_SCREEN"

}